const picture=[
  { 
    image:'./images/pic1.jpg',
    height:'200px',
    title:'笔记标题',
    name:'发表者',
    praise:'0'
  },
  { 
    image:'./images/pic2.jpg',
    height:'160px',
    title:'笔记标题',
    name:'发表者',
    praise:'0'
  },
  { 
    image:'./images/pic3.jpg',
    height:'100px',
    title:'笔记标题',
    name:'发表者',
    praise:'0'
  },
  { 
    image:'./images/pic4.jpg',
    height:'240px',
    title:'发表者',
    name:'cheng',
    praise:'0'
  },
  { 
    image:'./images/pic5.jpg',
    height:'220px',
    title:'发表者',
    name:'cheng',
    praise:'0'
  },
  { 
    image:'./images/pic6.jpg',
    height:'140px',
    title:'笔记标题',
    name:'发表者',
    praise:'0'
  },
  { 
    image:'./images/pic7.jpg',
    height:'200px',
    title:'笔记标题',
    name:'发表者',
    praise:'0'
  },
  { 
    image:'./images/pic8.jpg',
    height:'170px',
    title:'笔记标题',
    name:'发表者',
    praise:'0'
  },
  { 
    image:'./images/pic9.jpg',
    height:'140px',
    title:'笔记标题',
    name:'发表者',
    praise:'0'
  },
  { 
    image:'./images/pic5.jpg',
    height:'180px',
    title:'笔记标题',
    name:'发表者',
    praise:'0'
  },
  { 
    image:'./images/pic6.jpg',
    height:'120px',
    title:'笔记标题',
    name:'cheng',
    praise:'0'
  },
  { 
    image:'./images/pic7.jpg',
    height:'150px',
    title:'笔记标题',
    name:'发表者',
    praise:'0'
  },
  { 
    image:'./images/pic8.jpg',
    height:'130px',
    title:'笔记标题',
    name:'发表者',
    praise:'0'
  },
  { 
    image:'./images/pic9.jpg',
    height:'140px',
    title:'笔记标题',
    name:'发表者',
    praise:'0'
  },
  
]